### ISSUE TITLE
Implement running local cluster via CLI

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#328]
## Description

1. **CLI:** Implement command to quickly set up local Capact cluster. It might be split into two commands (see the "Possible options" section
1. **Website:** Use [https://github.com/asciinema/asciinema-player](https://github.com/asciinema/asciinema-player)  or [https://github.com/ines/termynal](https://github.com/ines/termynal) to display command for bootstrapping local Capact

Tasks:

- [x] Provision kind cluster - https://github.com/capactio/capact/pull/372
- [x] Install Capact
- [ ]  Use `capat env create kind` and `capact install` in our scripts

### Possible option

- Migrate our bash scripts to Go. Check before implementation if that is possible,  if not then fallback to previous idea (clone repo and use Bash scripts)
   * Clone subdirectory hack [https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository|smart-link)
 * Use charts from latest/stable helm repo
 * Provision command uses kind Go API
 * Git, kubectl, helm installed beforehand if not installed
    - Use SKIP_DEPS_INSTALLATION=true
    - For Git, we can check whether we can use go-git or GitHub CLI Golang API
    - Implement installation of kubectl, helm in our installation scripts
 * Add flag to specify release version (tag on git repo - by default latest release?)
 * Modify installation script to allow not building images
 * Update doc
     - development guide
     - local installation doc
 * Use it for local development
 * Use CLI on CI
    - PR: build cli from sources and  use it for integration tests
    - Branch: use CLI for integration tests

### Ideas

```bash
capact provision kind
capact install # by default latest semver git tag,
# alternatively
capact install --version @main/0.3.0/0.5.0
```

## Reason

Currently, there is no way to simply install Capact on local machine. You need to clone the repo, install required dependencies and run `make dev-cluster`. The steps should be improved and simplified.

This will help with getting users to get started quickly with the platform

 1. For development
 1. And experimentation / POC

**Comment by Trojan295** [comment]
Right now, I see a few open points:
1. If we want to use it also for development / CI set up, then we have to remember that our current scripts also build Docker images and upload them to the kind cluster to the flow would need to be:
   1. Build Docker images
   1. Create kind cluster using `capact provision kind`
   1. Upload Docker images to kind cluster
   1. Install Capact using `capact install`
   
   I think we could add a flag like `capact provision king --upload-images=<comma-seperated-list-of-images>` so we can upload the images after building for local development and CI.

2. For local development, `capact install` would need to support installing Capact charts from local file system. This could be also used on the CI, if we don't want to push Helm charts from every PR.

3. How about more environment-specific applications like FluentBit for integrating centralized logging to AWS Cloudwatch or EFS CSI driver chart? I would also argue, that other things liked our current prometheus-operator setup, is environment-specific and shouldn't be installed as part of Capact

   Different people could try to deploy Capact on existing Kubernetes deployments and different setups, and they would like to have only Capact, without the Prometheus, ingress controller or cert-manager deployments included. We already have a few places in the deployment scripts, where we apply different logic dependent on where we deploy Capact (kind / EKS / GCP), which is mostly due to some specific requirements (e.g. the EKS deployment we maintain has different cert-manager configuration).
   
   I think we should revisit this and decide what we ship as part of Capact, and what `capact install` should actually install.

**Comment by Trojan295** [comment]
Another point, after I started to check out the kind API to implement `capact provision kind`:

We would need to import their cobra.Command and tweak it, like we do with the `capact action watch` and Argo, as some of the method they call in the `cmd` is private in `internal` (`runtime` package in https://github.com/kubernetes-sigs/kind/blob/e3864c0be8cc3b17380d7d98d7f2632212ef79b6/pkg/cmd/kind/create/cluster/createcluster.go#L70).

It would be also good to provide a `capact deprovision kind`. Given those things, I would rather prepare an instruction on how to set up a kind cluster using their CLI, instead of embedding this in Capact CLI.

**Comment by mszostok** [comment]
**Brief answers from my side:**

1. We can do it as a part of install CLI. Think about:
  - `capact install --source @main/@latest` - installs the latest version from `main`
  - `capact install --source @source/@local` - builds docker images from local sources, uses local helm charts and uploads them to kind. Same as we have right now.
2. Yes.
3. Not sure what you want to do achieve. Currently, we have an opt to disable a given component, e.g. monitoring via env vars. In CLI we should port this functionality too. For example, have CLI flag which accepts disabled components list `capact install --disable-components="monitoring,cert-manager"`. By default, it installs all components as we have right now.
4. Not sure why you need to import their cobra, I create a small PoC and it works: https://github.com/capactio/capact/compare/main...mszostok:kind-poc?expand=1. Benefits:
  - Installation guide will be much easier.
  - We can easily maintain the kind cfg, k8s version that works with Capact etc.
  Importing their cobra is also and option, and I'm not against it as we will have the exact same API, which will be more friendly.
5. Yes, we should add `capact deprovision kind`. It first version, it will be as easy as removing the whole cluster without grace period or business shutdown (e.g. deprovision instances etc).
